-- Do not manually edit this file, it was auto-generated by Graphqelm
-- npm package version 2.0.0
-- Target elm package version 5.0.0
-- https://github.com/dillonkearns/graphqelm


module Swapi.Interface exposing (..)

{-| Type declarations used to give you type-safety so you only access types
from the appropriate interface.
@docs Character
-}


{-| Character
-}
type Character
    = Character
