-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Swapi.Interface exposing (..)

{-| Type declarations used to give you type-safety so you only access types
from the appropriate interface.
@docs Character
-}


{-| Character
-}
type Character
    = Character
