-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Swapi.Object exposing (..)

{-| Type declarations used to give you type-safety so you only access types
from the appropriate object.
@docs Droid, Human, ChatMessage
-}


{-| ChatMessage
-}
type ChatMessage
    = ChatMessage


{-| Droid
-}
type Droid
    = Droid


{-| Human
-}
type Human
    = Human
