-- Do not manually edit this file, it was auto-generated by Graphqelm
-- npm package version 2.0.0
-- Target elm package version 5.0.0
-- https://github.com/dillonkearns/graphqelm


module Swapi.Scalar exposing (..)

{-| Type constructors to build scalars. These data types are just wrappers
around strings, but their types carry semantic information from the server.
@docs Id
-}


{-| Id scalar
-}
type Id
    = Id String
